### ISSUE TITLE
Protect master branch

### ISSUE THREAD

**Issue by lsolesen** [troelskn/bucket#10]
@troelskn Could you protect the master branch so it can only be updated using pull requests?

**Comment by troelskn** [comment]
Done

**Comment by lsolesen** [comment]
master branch is still not protected. I was able to commit directly to it. Also could you enable Travis CI integration for Bucket?

**Comment by troelskn** [comment]
Description for the feature says: "Disables force-pushes to this branch and prevents it from being deleted." - So I presume that it is still possible to push, but not force-push/delete. I'll enable the status-check option, which should reject if checks don't pass.

**Comment by troelskn** [comment]
There - see if it works now?

**Comment by lsolesen** [comment]
@troelskn Hm. Did you enable Travis CI integration. I made a pull request, but nothing is happening.

**Comment by lsolesen** [comment]
@troelskn If you are tired of messing around with this, you can make me an admin :/

**Comment by lsolesen** [comment]
@troelskn Did you enable TravisCI testing?
